services:
  - name: web
    type: web
    env: static
    buildCommand: cd packages/web && npm ci && npm run build
    staticPublishPath: packages/web/dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
  - name: server
    type: web
    env: node
    buildCommand: cd packages/server && npm ci && npm run build
    startCommand: cd packages/server && npm start
    region: singapore
    plan: free
    envVars:
      - key: PORT
        value: 8081
