on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cd packages/web && npm install
      - run: cd packages/web && npm run type-check
      - run: cd packages/server && npm install
      - run: cd packages/server && npm run type-check
      - run: npm install
      - run: npm run lint
